export const TOGGLE_TRASH = 'TOGGLE_TRASH'

export const TOGGLE_TOOLBAR = 'TOGGLE_TOOLBAR'

export const UPDATE_TOOLBAR_ICON = 'UPDATE_TOOLBAR_ICON'

export const DELETE_TOOLBAR_ICON = 'DELETE_TOOLBAR_ICON'

export const SWITCH_TOOLBAR_ICONS = 'SWITCH_TOOLBAR_ICONS'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_SELECTED_ICON = 'SET_SELECTED_ICON'

export const SET_SELECTED_TAB = 'SET_SELECTED_TAB'

export const CLEAR_TOOLBAR = 'CLEAR_TOOLBAR'