export const ADD_PLACE = 'ADD_PLACE'

export const DELETE_PLACE = 'DELETE_PLACE'

export const EDIT_PLACE_CATEGORY = 'EDIT_PLACE_CATEGORY'

export const CLEAR_PLACE_CATEGORY = 'CLEAR_PLACE_CATEGORY'

export const UPDATE_PLACE_NOTE = 'UPDATE_PLACE_NOTE'

export const SET_USER_INFO = 'SET_USER_INFO'

export const UPDATE_PLACE = 'UPDATE_PLACE'

export const LOAD_LOCAL_INFO = 'LOAD_LOCAL_INFO'

export const LOGOUT = 'LOGOUT'
